import { useEffect, useState } from 'react'
import { Activity, Bot, ChevronDown, ChevronRight, CircleAlert, Folder, GitBranch, Plus, Search, Send, Square, Terminal, X } from 'lucide-react'
import { mockRuntime } from './mock/runtime'
import type { SessionDetail, SessionStatus, ToolCall } from './shared/types'
import './styles.css'

const statusLabel: Record<SessionStatus, string> = { idle: 'Idle', running: 'Running', waiting_approval: 'Approval', completed: 'Completed', failed: 'Failed' }
function Status({ status }: { status: SessionStatus }) { return <span className={`status status-${status}`}><i />{statusLabel[status]}</span> }
function ToolCard({ tool }: { tool: ToolCall }) { const [open, setOpen] = useState(false); return <article className="tool-card"><button className="tool-head" onClick={() => setOpen(!open)}>{open ? <ChevronDown size={15} /> : <ChevronRight size={15} />}<Terminal size={15} /><b>{tool.name}</b><span className={`tool-state tool-${tool.status}`}>{tool.status}</span>{tool.duration && <small>{tool.duration}</small>}</button>{open && <div className="tool-body"><pre>{JSON.stringify(tool.input, null, 2)}</pre>{tool.output && <pre className="output">{tool.output}</pre>}{tool.error && <div className="error"><CircleAlert size={14} />{tool.error}</div>}</div>}</article> }
function Sidebar({ sessions, selected, onSelect, onNew }: { sessions: SessionDetail[]; selected: string; onSelect: (id: string) => void; onNew: () => void }) { const [query, setQuery] = useState(''); return <aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><div><strong>Bel</strong><small>agent harness</small></div></div><button className="new-button" onClick={onNew}><Plus size={16} />New session</button><label className="search"><Search size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search sessions" /></label><div className="session-list">{sessions.filter((s) => s.title.toLowerCase().includes(query.toLowerCase())).map((session) => <button className={`session-item ${selected === session.id ? 'selected' : ''}`} key={session.id} onClick={() => onSelect(session.id)}><div className="session-title"><span>{session.title}</span><Status status={session.status} /></div><small><Folder size={12} />{session.workspacePath}</small><small className="muted"><GitBranch size={12} />{session.provider} · {session.model}</small></button>)}</div></aside> }
function Inspector({ session }: { session: SessionDetail }) { const [tab, setTab] = useState('Overview'); return <aside className="inspector"><div className="inspector-title">Session inspector</div><nav>{['Overview', 'Tools', 'Files', 'Events'].map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav>{tab === 'Overview' && <div className="facts">{[['Session ID', session.id], ['Workspace', session.workspacePath], ['Provider', session.provider], ['Model', session.model], ['Messages', String(session.messages.length)], ['Tool calls', String(session.toolCalls.length)]].map(([label, value]) => <div className="fact" key={label}><small>{label}</small><span>{value}</span></div>)}</div>}{tab === 'Tools' && <div className="inspector-list">{session.toolCalls.map((tool) => <div key={tool.id}><Terminal size={14} /><span>{tool.name}</span><em>{tool.status}</em></div>)}</div>}{tab === 'Files' && <div className="inspector-list">{session.files.map((file) => <div key={file.path}><Folder size={14} /><span>{file.path}</span><em>{file.kind}</em></div>)}</div>}{tab === 'Events' && <div className="events">{session.events.map((event) => <div key={event.id}><Activity size={14} /><div><b>{event.type}</b><small>{event.message}</small></div></div>)}</div>}</aside> }
function App() { const [sessions, setSessions] = useState<SessionDetail[]>([]); const [selected, setSelected] = useState(''); const [session, setSession] = useState<SessionDetail | null>(null); const [text, setText] = useState(''); useEffect(() => { void mockRuntime.listSessions().then(async (list) => { const details = await Promise.all(list.map((item) => mockRuntime.getSession(item.id))); const valid = details.filter((item): item is SessionDetail => item !== null); setSessions(valid); setSelected(valid[0]?.id ?? '') }) }, []); useEffect(() => { if (selected) void mockRuntime.getSession(selected).then(setSession) }, [selected, sessions]); const refresh = async () => { const list = await mockRuntime.listSessions(); const details = await Promise.all(list.map((item) => mockRuntime.getSession(item.id))); setSessions(details.filter((item): item is SessionDetail => item !== null)); }; const send = async () => { if (!session || !text.trim()) return; await mockRuntime.sendMessage(session.id, text.trim()); setText(''); await refresh() }; const create = async () => { const created = await mockRuntime.createSession(); await refresh(); setSelected(created.id) }; return <div className="app"><Sidebar sessions={sessions} selected={selected} onSelect={setSelected} onNew={() => void create()} /><main className="main">{session ? <><header className="conversation-header"><div><h1>{session.title}</h1><span><Folder size={13} />{session.workspacePath}</span></div><div className="header-meta"><Status status={session.status} /><span>{session.provider} / {session.model}</span></div></header><section className="transcript">{session.messages.length === 0 ? <div className="empty"><Bot size={30} /><h2>What should Bel do?</h2><p>Describe a task and the agent workspace will appear here.</p></div> : session.messages.map((message) => <div className={`message message-${message.role}`} key={message.id}><div className="avatar">{message.role === 'user' ? 'You' : <Bot size={16} />}</div><div><small>{message.role}</small><p>{message.content}</p></div></div>)}{session.toolCalls.map((tool) => <ToolCard key={tool.id} tool={tool} />)}</section><div className="composer"><textarea value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void send() } }} placeholder="Ask Bel to inspect or modify your project…" /><div><span>Enter to send · Shift+Enter for newline</span><button className="icon-button"><Square size={14} /></button><button className="send-button" onClick={() => void send()}><Send size={15} />Send</button></div></div></> : <div className="empty">Loading Bel…</div>}</main>{session && <Inspector session={session} />}</div> }
export default App
